version: "3"
networks:
  esportsbattle_net:
    driver: bridge
services:
  db:
    image: postgres
    container_name: esportsbattle_postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=esportsbattle_matches
      - POSTGRES_USER=esports
      - POSTGRES_PASSWORD=keepsecret
    ports:
      - 5432:5433
    networks:
      - esportsbattle_net
  app:
    build: .
    container_name: esportsbattle_aggregator_server
    restart: always
    command: ["python", "start_app.py"]
    volumes:
      - ./docker-logs:/app/logs
    ports:
      - "11011:11011"
    environment:
      - POSTGRES_USERNAME=esports
      - POSTGRES_PASSWORD=keepsecret
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=esportsbattle_matches
      - APP_PORT=11011
      - UPDATE_TIMEOUT=60
    depends_on:
      - db
    networks:
      - esportsbattle_net