version: "3"
networks:
  esportsbattle_net:
    driver: bridge
services:
  db:
    image: postgres
    container_name: esportsbattle_postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - 5432:5432
    networks:
      - esportsbattle_net
  app:
    build: .
    container_name: esportsbattle_aggregator_server
    restart: always
    command: ["python", "start_app.py"]
    volumes:
      - ./docker-logs:/app/logs
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - APP_PORT=${APP_PORT}
      - UPDATE_TIMEOUT=${UPDATE_TIMEOUT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - esportsbattle_net